# This is a basic workflow to help you get started with Actions
name: .NET Core Desktop

# Controls when the action will run. Triggers the workflow on oush or pull request
# events but only for the master branch
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [windows-latest]
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
        
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0
      
    - name: Restore Nuget packages
      run: nuget restore CV.sln
      
    - name: Build the Solution
      run: msbuild CV.sln
      
    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
